# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-HTTP
version:      0.11
version_from: lib/Test/HTTP.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Field:                  0
    Filter::Simple:                0
    LWP::UserAgent:                0
    Test::Builder::Module:         0
    Test::More:                    0
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
